---
- name: Install keepalived
  ansible.builtin.package:
    name: keepalived
    state: present
  tags: keepalived
  notify: Restart keepalived

- name: Add keepalived configuration files from templates
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('root') }}"
  loop: "{{ keepalived_templates }}"
  tags: keepalived
  notify: Restart keepalived
